Compile under CentOS 7.8
greenbone/gvm-libs pull request #396
Opened 2020-08-31 12:40 UTC by tuxmaster5000

Fix for
https://github.com/greenbone/gvm-libs/issues/395

2020-08-31 16:15 UTC, mattmundell requested changes
Thanks.

Do you want this in 20.08.x?  If so we should change the destination branch to greenbone:gvm-libs-20.08.

And please add a CHANGELOG.md entry.

2020-08-31 16:15 UTC, mattmundell commented on boreas/CMakeLists.txt
> +  add_compile_options(-std=gnu99)
```suggestion
    add_compile_options(-std=gnu99)
```

2020-08-31 16:15 UTC, mattmundell commented on boreas/CMakeLists.txt
> +  endif()
```suggestion
  endif(${GLIB_VERSION} VERSION_LESS "2.50.3")
```

2020-08-31 16:15 UTC, mattmundell commented on boreas/CMakeLists.txt
> +endif()
```suggestion
endif(CMAKE_C_COMPILER_ID STREQUAL "GNU")
```

2020-08-31 16:16 UTC, mattmundell commented
Also, would be great to have a little comment about why this is required.

2020-09-01 04:56 UTC, tuxmaster5000 commented
> Also, would be great to have a little comment about why this is required.

See the the issue link, why it is needed. It looks like the code was only tested again an very new version of glibc.

2020-09-01 06:31 UTC, bjoernricks commented
> See the the issue link, why it is needed. It looks like the code was only tested again an very new version of glibc.

Our base system is Debian as you can see from our CI images. Therefore nearly all Distributions based on Debian will work without any issues. We can't invest our resources for supporting all kind of other distributions. Therefore we rely on external contributors like you to provide patches if something breaks.

2020-09-01 09:00 UTC, tuxmaster5000 commented
> > See the the issue link, why it is needed. It looks like the code was only tested again an very new version of glibc.
> 
> Our base system is Debian as you can see from our CI images. Therefore nearly all Distributions based on Debian will work without any issues. We can't invest our resources for supporting all kind of other distributions. Therefore we rely on external contributors like you to provide patches if something breaks.

This is no problem,  because it is not my first patch for the greenbone world. :)

2021-08-18 11:57 UTC, bjoernricks approved these changes

2021-08-18 11:58 UTC, merged