SC 434
greenbone/gvm-libs pull request #672
Opened 2022-03-31 10:02 UTC by nichtsfrei

- Refactor: boreas split two seconds wait into smaller pieces
- Refactor: multiply wait for replies by 3 and send icmp by 10

2022-04-04 06:18 UTC, ArnoStiefvater requested changes

2022-04-04 06:18 UTC, ArnoStiefvater commented on boreas/alivedetection.c
> +          if (number_of_targets
```suggestion
      for (int i = 0; i < max_wait_rounds; i++)
        {
          /* If all targets are already identified as alive we do not need to
          wait for replies anymore.*/
          if (number_of_targets
```

2022-04-04 06:18 UTC, ArnoStiefvater commented on boreas/alivedetection.c
>         * for replies anymore.*/
```suggestion
```

2022-04-04 13:42 UTC, nichtsfrei commented on boreas/ping.c
> +      usleep (10 * 1000);
I use prefs_get `ICMP_RETRIES` and `ICMP_GRACE_PERIOD` to define those. Need to extend openvas.conf afterwards.

2022-04-04 13:42 UTC, nichtsfrei commented on boreas/sniffer.c
> +#include <asm-generic/errno-base.h>
Nope

2022-04-06 08:41 UTC, ArnoStiefvater commented on boreas/ping.c
> +      (tmp = prefs_get ("ICMP_GRACE_PERIOD")) != NULL ? atoi (tmp) : 0;
```suggestion
      (tmp = prefs_get ("icmp_grace_period")) != NULL ? atoi (tmp) : 0;
```
All prefs in man page a lower case.

2022-04-06 08:41 UTC, ArnoStiefvater commented on boreas/ping.c
> +         (tmp = prefs_get ("ICMP_RETRIES")) != NULL ? atoi (tmp) : 1)
```suggestion
         (tmp = prefs_get ("icmp_retries")) != NULL ? atoi (tmp) : 1)
```
All prefs in man page a lower case.

2022-04-07 09:48 UTC, merged